apiVersion: v1
kind: Service
metadata:         # 0 spaces
  name: day15-service   # 2 spaces
spec:             # 0 spaces
  type: NodePort        # 2 spaces
  selector:             # 2 spaces
    app: day15-app      # 4 spaces
  ports:                # 2 spaces
    - protocol: TCP     # 2 spaces + "- " = 4 total
      port: 3000        # 6 spaces
      targetPort: 3000  # 6 spaces
      nodePort: 30001   # 6 spaces